### ISSUE TITLE
Try to re-write ubermini_2.stan with cholesky decomp

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/pmm#11]
See ubermini_2.R (note you need to change parameter `m` as noted in the code). This relates [OSPREE issue 388](https://github.com/lizzieinvancouver/ospree/issues/388). If much preferred you can play with code there (see ../phylogeny/compare_ospreedat_ubermini_2.R).

See 'Optimization through Cholesky Factorization' [in Stan manual](https://mc-stan.org/docs/2_18/stan-users-guide/multivariate-hierarchical-priors-section.html)

Some maybe or maybe not useful posts from Stan Discourse:

"We did write that multi_normal_lpdf. But the point is that the multivariate normal requires the covariance matrix to be positive definite in order to have a proper distribution. With semidefinite covariance, you’re restricted to a submanifold that will be up to you to enforce with constraints. We’ve found soft constraints get the job done and are better than hard constraints in some of these cases, like in spatial ICAR models, which are also improper due to semidefiniteness, but they only have a single rank of deficiency which can be made up by assuming a sum-to-zero constraint on the parameters." from  [Stan Discourse here](https://discourse.mc-stan.org/t/stans-pickyness-regarding-covariance-matrices/5067/2)

"if you haven’t tried already, you may find it helpful to reparameterize the covariance matrices using the Cholesky decomposition." and useful links! [here](https://discourse.mc-stan.org/t/hierarchical-multivariate-normal-model/9167/5)

@legault to keep us cross-referenced!

**Comment by FaithJones** [comment]
I tried to add a Cholesky decomposition, but no luck. I am not sure if I wrote the code wrong or if this was not the solution. The code is in stan/ubermini_2_Chol.stan. I got an error about positive definite matrices when I ran it.

**Comment by legault** [comment]
@FaithJones @lizzieinvancouver Function "cholesky_decompose()" in Stan requires a positive definite matrix, so this may explain why the ubermini_2_Chol.stan version is still running into problems. See commit d85d59e for an initial value function that may avoid the problem we're having

**Comment by lizzieinvancouver** [comment]
@FaithJones Could you try your code again on first the current ubermini_2.R which has a nice f(x) Geoff wrote that helps with initial conditions and check that you get the right params back.

Then if that works, can we try it on phlyo_opsree_compact.R (lessmini_threeslopeintercept.stan)? I am getting structure in `sigma_interceptsbf` and `sigma_interceptsbp` that I cannot get rid of with more warmup or `adapt_delta` and hoping we can fix it. See also issue #13.

We can discuss a little Wednesday at lab meeting hopefully.

**Comment by lizzieinvancouver** [comment]
@FaithJones Any chance you could play around with the cholesky soon? I'd like to know how it performs before trying other strategies to fix the divergences. Thank you!

**Comment by FaithJones** [comment]
I tried adding a cholensky to lambda_vcv to ubermini_bigpriors.stan (see ubermini_2_Chol_biggerpriors.stan). It didn't work - I get the error " Exception: validate transformed params: L_lambda_vcv is not a valid unit vector. The sum of the squares of the elements should be 1, but is ...)". I also noticed there is an extra matrix in the code now (sigma_mat). Its possible this difference is affecting my code, but I am not sure.

**Comment by lizzieinvancouver** [comment]
@FaithJones Thanks! 

Using git's helpful, but highly judgmentally named blame f(x) I can see Geoff added that [code a few months ago](https://github.com/lizzieinvancouver/pmm/blame/master/analyses/stan/ubermini_2_biggerpriors.stan), while making some helpful tweaks and fixes.

I tried replacing it with the older code:
```
functions {
  matrix lambda_vcv(matrix vcv, real lambda, real sigma){
    matrix[rows(vcv),cols(vcv)] local_vcv;
    local_vcv = vcv * lambda;
    for(i in 1:rows(local_vcv))
      local_vcv[i,i] = vcv[i,i];
    return(local_vcv * sigma);
  }
}
```
in your ubermini_2_Chol_biggerpriors.stan, and got an initial conditions issue. 

@legault Could you possibly take a look at this in the next week or so? I didn't push my code as it's not much of a fix, but as you're the one who managed to fix the initial conditions issue before, and definitely ahead of me on linear algebra I am thinking you'll have more insight. Help would be much appreciated!

**Comment by lizzieinvancouver** [comment]
@legault Could you take a look at running @FaithJones code? I tried running it from [ubermini_2.R](https://github.com/lizzieinvancouver/pmm/blob/master/analyses/ubermini_2.R) but updating it to use [her Stan code]https://github.com/lizzieinvancouver/pmm/blob/master/analyses/stan/ubermini_2_Chol_biggerpriors.stan) and updating that Stan code with the older code snippet mentioned above. When I run it I get an initial conditions issue, but please see where you end up. Thank you!

**Comment by legault** [comment]
I think the unsatisfying answer is that for some parameter values, the Cholesky decomposition of the matrix made by the lambda_vcv function is not a [unit vector](https://mc-stan.org/docs/2_26/stan-users-guide/unit-vectors.html).

Why it isn't a unit vector, I'm not sure. One possibility is that due to numerical problems, the matrix being decomposed is not positive definite. Recall that we're building the matrix first (based on the phylogenetic tree and estimated lambda/sigma) and this new code then decomposes that matrix, so if the built matrix is not of the appropriate type, the decomposition will fail.

The examples that I've seen which use the Cholesky decomposition generally try to estimate all elements of the Cholesky factor, whereas we're only trying to estimate certain parts of those elements (the parts associated with sigma and lambda). Therefore unless we can, for lack of a better phrasing, "decompose" the Cholesky factor into its phylogenetic parts and sigma/lambda parts, and combine them in a way that ensures the result is a unit vector, I'm not sure the decomposition will help us.

Note I've had success getting back the parameter values in ubermini_2 using a no intercept version of the Stan models from an earlier commit (i.e., no divergences and they return the correct values). See "lessmini_oneslope.R" and "lessmini_oneslope.stan" in 3c06992. 

The other models from adfd84d (1, 2, and 3 slope versions) seem to behave well too, so maybe we can use those.

**Comment by lizzieinvancouver** [comment]
@legault Thanks! 

Can you take a look at the model running the OSPREE data and make sure all your suggested fixes are in? It's in [analyses/phylo_ospree_compact.R](https://github.com/lizzieinvancouver/pmm/blob/master/analyses/phlyo_opsree_compact.R) and runs stan/nointer_2levelphyall_2 which *I think* I based off ubermini_2_biggerpriors.stan (you'll see in the code I build up to the full model we want). If all the fixes are in and you have any other ideas insights or thoughts, please let us know.

**Comment by legault** [comment]
Yes, in 4470044 I've fit the oneslope models (slope only, slope + intercept) to the OSPREE data [forcing]. The slope only model has 0 divergences and seems to return sensible estimates. The slope + intercept model has only a few divergences which I think can fix with better priors.
