### ISSUE TITLE
error in inverseA

### ISSUE THREAD

**Issue by legault** [lizzieinvancouver/pmm#5]
@lizzieinvancouver I have encountered an error while running line 109 of file "run_MCMCbrms_pglmm.R" for nspecies = 40 and nindividuals = 40:

>inter.mat.inflated <- inflate.mat(simd$intermat,nspecies,nindividuals)

Produces the following error message:

> Error in inverseA(pedigree = pedigree, scale = scale, nodes = nodes) : 
  phylogeny tip/node labels are not unique

I have made no other changes to the code.

**Comment by lizzieinvancouver** [comment]
@legault Ah, shoot -- I think I know what that is. The underlying code uses a-z as names so we probably cannot go above 24. For now could you do nspecies = 10 and nindividuals = 10 instead of 40? Same change for @cchambe12 @FaithJones if you were assigned any sims with nspecies = 40 and nindividuals = 40.  Thanks for catching this and my apologies.

@MoralesCastilla This is something we should fix in the longer term.

**Comment by legault** [comment]
Sure thing, I'll run with n = 10.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @legault 

Sorry about this, I've fixed the code `pmm-get-simulated-data.R` within the source folder to allow for a different number of species and individuals. I imagine something similar should be fixed for `pmm-get-simulated-data-nointra` and `pmm-get-simulated-data-nointra-joly`. Let me know if this works.

**Comment by lizzieinvancouver** [comment]
I think this was working last I checked!
